# Generated by Django 2.0.7 on 2018-08-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='تلفن همراه'),
        ),
    ]
