# Generated by Django 2.0.7 on 2018-08-03 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='دسته')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام محصول')),
                ('photo', models.ImageField(upload_to='', verbose_name='تصویر')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('description', models.TextField(max_length=500, verbose_name='توضیحات')),
                ('inventory', models.IntegerField(default=0, verbose_name='موجودی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name='دسته')),
            ],
        ),
    ]
